// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIz3a12C9GaBkH9SqNcUkxn83B366WG9o',
    appId: '1:583994139855:web:1fcf3ca0aedbb9f8e603ba',
    messagingSenderId: '583994139855',
    projectId: 'konsuldoc-89891',
    authDomain: 'konsuldoc-89891.firebaseapp.com',
    storageBucket: 'konsuldoc-89891.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BGT7qmhzddn_hTnAB3vWwFq-B5I9s80',
    appId: '1:583994139855:android:24548084801cf90fe603ba',
    messagingSenderId: '583994139855',
    projectId: 'konsuldoc-89891',
    storageBucket: 'konsuldoc-89891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLxSMxIdM-dUBj2_cn1LP867Sl3gWaylA',
    appId: '1:583994139855:ios:5d024df42d330f3be603ba',
    messagingSenderId: '583994139855',
    projectId: 'konsuldoc-89891',
    storageBucket: 'konsuldoc-89891.appspot.com',
    iosBundleId: 'com.example.konsuldoc',
  );
}